### ISSUE TITLE
consider moving hard-coded styles into a styles.css file

### ISSUE THREAD

**Issue by danmarsden** [redesitos/moodle-tool_untoken_oauth2#10]
we try to avoid using "style" tags within in-line code and put css into a styles.css file within the plugin - it makes it easier for theme developers to override any css within the plugin,

you might consider tidying that up in your mform class.

this won't prevent plugins db approval though - so feel free to close as "won't fix" if you don't want to do this.

**Comment by redesitos** [comment]
Thanks, the style is adjust
