### ISSUE TITLE
consider deleting "empty" files

### ISSUE THREAD

**Issue by danmarsden** [redesitos/moodle-tool_untoken_oauth2#11]
files like upgradelib.php/uninstall.php/install.php are not "required" to be within your plugin, so if they aren't doing anything useful it might be worth just deleting them from your plugin.

note - this isn't a blocker for approval in the plugins db.

**Comment by danmarsden** [comment]
also tests/test_test.php doesn't seem to be doing anything.

**Comment by redesitos** [comment]
Hi, the files upgradelib.php, uninstall.php, install.php and test.php have been deleted.
