### ISSUE TITLE
incorrect bug tracker link in plugins db

### ISSUE THREAD

**Issue by danmarsden** [redesitos/moodle-tool_untoken_oauth2#3]
Hi Jonathan, sorry for the delay in reviewing your plugin! - it's taken a bit of time to get near the top of our queue! :-)
Please add yourself as a watcher to the issue related to the plugins review as we'll post final status updates there. Do this by clicking on the "start watching this issue" after logging in.
https://tracker.moodle.org/browse/CONTRIB-7840

Once you've done that ... can you please update the moodle.org plugins db entry and point the "bug tracker" link to the tracker here in github - not the moodle tracker issue with the feature request - although you could link to that tracker in your readme or description if you wanted. Then - close this issue to let us know you have fixed it! :-)

**Comment by redesitos** [comment]
The tracker link in the information has been adjusted as you indicated, many thanks
