### ISSUE TITLE
repository name doesn't follow normal moodle conventions.

### ISSUE THREAD

**Issue by danmarsden** [redesitos/moodle-tool_untoken_oauth2#4]
The standard convention for git repository name uses the "frankenstyle" naming convention in Moodle - if you have a look around at other repositories you'll see this used. Following this convention makes it a lot easier for moodle admins to indentify your plugin and where it should be installed.

The "correct" name for your repository would be "moodle-tool_untoken_oauth2" - not "moodle_untoken_oauth2"

**Comment by redesitos** [comment]
Thanks, the repository has changed.
