### ISSUE TITLE
incorrect install.xml file

### ISSUE THREAD

**Issue by danmarsden** [redesitos/moodle-tool_untoken_oauth2#6]
It looks like your install.xml file has been generated by hand or copy/pasted incorrectly 

to fix this up  se the xmldb editor to load the install.xml file, make a change like adding some text to the descriptoin, and then use the xmldb editor built in tools to save the file. You may need to change the file permissions on disk so that xmldb can save it directly.

more info on the xmldb editor is here:
https://docs.moodle.org/dev/Using_XMLDB

**Comment by danmarsden** [comment]
along with this - the table name you have used is incorrect. the table name needs to be prefixed with the frankenstyle plugin name. "tool_untoken_oauth2" - a more correct name would be "tool_untoken_oauth2_log"

**Comment by redesitos** [comment]
Hi, the issue has fixed.

Many thanks.

**Comment by danmarsden** [comment]
great! - make sure you upload the new version to the plugins db when you are ready for us to take another look!
