### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [redesitos/moodle-tool_untoken_oauth2#7]
Moodle implements a privacy api - it would be nice if you could implement this in your plugin. Sites that use continuous integration processes will not be able to use your plugin as Moodle includes unit tests to check that all installed plugins contain appropriate privacy classes.
more information on the privacy api is here:
https://docs.moodle.org/dev/Privacy_API

please note - this is not a blocker for approval in the plugins db but would be nice to add at some point.

**Comment by redesitos** [comment]
Thanks, y have read the api to implement in next release

**Comment by redesitos** [comment]
Hello, the privacy addition has been made in the plugin with the corresponding information.

Thanks a lot.
