### ISSUE TITLE
incorrect class names used in forms.

### ISSUE THREAD

**Issue by danmarsden** [redesitos/moodle-tool_untoken_oauth2#9]
All classes should be namespaced within the classes folder under the plugin namespace, or prefixed with the frankenstyle prefix name.

for example your class "sform" in class/sform.php could be namespaced in tool_untoken_oauth2

- here's an example class from another tool plugin that is namespaced:
https://github.com/moodle/moodle/blob/master/admin/tool/analytics/classes/clihelper.php#L25

Or alternatively (the old method but still ok for plugins db) is to prefix the name of the class with the plugin name like
class tool_untoken_oauth2_sform

This prevents class name collisions with other plugins and core code - you can't expect that another core file or plugin won't use the same class name which might cause a fatal error.

**Comment by redesitos** [comment]
Hello, I have done the namespace process for the classes as you indicated, thanks.
